services:
  smart-news-aggregator-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5050:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_ENV_FILE=.env.prod
    env_file:
      - .env.prod